import os
import sys
import pytest

# Ensure we can import ingest
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from ingest import ingest_cluster

def test_live_ingestion():
    # Setup
    output_path = "test-live-output.json"
    if os.path.exists(output_path):
        os.remove(output_path)
    
    # Execute the ingest process against the live cluster
    # Assuming kind is running and context is set (handled by PS1 script)
    graph_data = ingest_cluster(output_path=output_path, live_cve=False)
    
    assert graph_data is not None, "Graph data must not be None"
    assert "nodes" in graph_data, "Graph data must contain 'nodes' key"
    assert "edges" in graph_data, "Graph data must contain 'edges' key"
    
    nodes = graph_data["nodes"]
    edges = graph_data["edges"]

    # Map for easy assertion
    node_names = { n.get("metadata", {}).get("name", n.get("label", n["id"])): n for n in nodes }

    # The deterministic test resources should have been ingested
    assert "test-sa" in node_names, "ServiceAccount 'test-sa' missing from graph"
    assert "test-secret-password" in node_names, "Secret 'test-secret-password' missing"
    assert "test-config" in node_names, "ConfigMap 'test-config' missing"
    assert "secret-reader-role" in node_names, "Role 'secret-reader-role' missing"
    assert "read-secrets-binding" in node_names, "RoleBinding 'read-secrets-binding' missing"
    assert "test-pod" in node_names, "Pod 'test-pod' missing"
    
    # Verify Risk Scoring Logic based on known heuristics in ingest.py
    # "test-secret-password" should be 'crown-jewel' because it has 'password' key
    secret_node = node_names["test-secret-password"]
    assert secret_node["risk_level"] == "crown-jewel", "Secret risk level should be crown-jewel"
    
    # "test-pod" has ports=80 so risk_level=medium or critical depending on CVE lookups, 
    # but since live_cve=False, fallback heuristics should make it 'medium' due to exposed port.
    pod_node = node_names["test-pod"]
    assert pod_node["type"] == "pod"
    assert pod_node["risk_level"] in ["medium", "high", "critical"], "Pod with port 80 must have elevated risk"
    
    # Verify Edges generated by relationship logic
    # 1. Pod -> ServiceAccount (uses_service_account)
    pod_id = pod_node["id"]
    sa_id = node_names["test-sa"]["id"]
    pod_to_sa = [e for e in edges if e["source"] == pod_id and e["target"] == sa_id and e["relationship"] == "uses_service_account"]
    assert len(pod_to_sa) >= 1, "Edge missing: Pod -> ServiceAccount"
    
    # 2. ServiceAccount -> Binding (bound_by) -> wait, actually ingest.py edge points from Subject to RoleBinding
    # Let's check ingest.py line 235: source=s_uid target=uid relationship=bound_by
    # Subject -> RoleBinding
    binding_id = node_names["read-secrets-binding"]["id"]
    sa_to_binding = [e for e in edges if e["source"] == sa_id and e["target"] == binding_id and e["relationship"] == "bound_by"]
    assert len(sa_to_binding) >= 1, "Edge missing: ServiceAccount -> RoleBinding"
    
    # 3. RoleBinding -> Role (grants)
    role_id = node_names["secret-reader-role"]["id"]
    binding_to_role = [e for e in edges if e["source"] == binding_id and e["target"] == role_id and e["relationship"] == "grants"]
    assert len(binding_to_role) >= 1, "Edge missing: RoleBinding -> Role"
    
    # 4. Role -> Secret (can_access)
    secret_id = secret_node["id"]
    role_to_secret = [e for e in edges if e["source"] == role_id and e["target"] == secret_id and e["relationship"] == "can_access"]
    assert len(role_to_secret) >= 1, "Edge missing: Role -> Secret"
    
    # Cleanup output
    if os.path.exists(output_path):
        os.remove(output_path)
    
if __name__ == "__main__":
    pytest.main(["-v", __file__])
